export {default as HomePage} from './HomePage'
export {default as Page404} from './Page404'
export {default as Page500} from './Page500'
export {default as Authorization} from './Authorization'
export {default as Registration} from './Registration'
export {default as PersonalInfo} from './PersonalInfo'
export {default as PersonalInfoEdit} from './PersonalInfoEdit'
